# Generated by Django 2.1.1 on 2018-09-05 15:45

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('recipe', '0003_auto_20180904_2059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Recipe',
        ),
    ]

