# Generated by Django 2.1.1 on 2018-09-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20180905_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=100)),
                ('ingredient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='recipe_ingredients',
            name='recipe_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipes'),
        ),
        migrations.AddField(
            model_name='recipe_ingredients',
            name='unit_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Units'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='unit_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Units'),
        ),
    ]
