# Generated by Django 2.1.1 on 2018-09-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20180905_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredients',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
