# Generated by Django 2.1.1 on 2018-09-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20180905_1631'),
    ]


