# Generated by Django 2.1.1 on 2018-09-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20180905_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ingredient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Ingredient')),
                ('recipe_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='unit_name',
        ),
        migrations.RemoveField(
            model_name='recipe_ingredients',
            name='ingredient_name',
        ),
        migrations.RemoveField(
            model_name='recipe_ingredients',
            name='recipe_name',
        ),
        migrations.RemoveField(
            model_name='recipe_ingredients',
            name='unit_name',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Recipe_ingredients',
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='unit_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Unit'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Unit'),
        ),
    ]
