# Generated by Django 2.1.1 on 2018-09-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20180905_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_ingredient',
            old_name='ingredient_name',
            new_name='ingredient_id',
        ),
        migrations.RenameField(
            model_name='recipe_ingredient',
            old_name='recipe_name',
            new_name='recipe_id',
        ),
        migrations.RenameField(
            model_name='recipe_ingredient',
            old_name='unit_name',
            new_name='unit_id',
        ),
    ]
