# Generated by Django 2.1.1 on 2018-09-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20180905_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_ingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipe_ingredient',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipe_ingredient',
            old_name='unit_id',
            new_name='unit',
        ),
    ]
