# Generated by Django 2.1 on 2018-09-07 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_ingredient_unit_acmount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit_acmount',
            new_name='unit_amount',
        ),
    ]
